<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.335">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Solomon Chak">
<meta name="dcterms.date" content="2023-02-27">

<title>R Intro</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="R_intro_files/libs/clipboard/clipboard.min.js"></script>
<script src="R_intro_files/libs/quarto-html/quarto.js"></script>
<script src="R_intro_files/libs/quarto-html/popper.min.js"></script>
<script src="R_intro_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="R_intro_files/libs/quarto-html/anchor.min.js"></script>
<link href="R_intro_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="R_intro_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="R_intro_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="R_intro_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="R_intro_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#using-r-in-rstudio-locally-or-online" id="toc-using-r-in-rstudio-locally-or-online" class="nav-link active" data-scroll-target="#using-r-in-rstudio-locally-or-online">Using R in RStudio locally or online</a>
  <ul class="collapse">
  <li><a href="#installation-or-sign-up" id="toc-installation-or-sign-up" class="nav-link" data-scroll-target="#installation-or-sign-up">Installation or sign up</a></li>
  <li><a href="#project-setup-and-file-transfer" id="toc-project-setup-and-file-transfer" class="nav-link" data-scroll-target="#project-setup-and-file-transfer">Project setup and file transfer</a></li>
  <li><a href="#the-rstudio-interface" id="toc-the-rstudio-interface" class="nav-link" data-scroll-target="#the-rstudio-interface">The RStudio Interface</a></li>
  <li><a href="#using-packages" id="toc-using-packages" class="nav-link" data-scroll-target="#using-packages">Using packages</a></li>
  </ul></li>
  <li><a href="#importing-data-into-r" id="toc-importing-data-into-r" class="nav-link" data-scroll-target="#importing-data-into-r">Importing data into R</a>
  <ul class="collapse">
  <li><a href="#preparing-a-.csv-file-from-excel" id="toc-preparing-a-.csv-file-from-excel" class="nav-link" data-scroll-target="#preparing-a-.csv-file-from-excel">Preparing a .csv file from Excel</a></li>
  <li><a href="#loading-a-.csv-file-into-r" id="toc-loading-a-.csv-file-into-r" class="nav-link" data-scroll-target="#loading-a-.csv-file-into-r">Loading a .csv file into R</a></li>
  <li><a href="#loading-an-excel-file-directly" id="toc-loading-an-excel-file-directly" class="nav-link" data-scroll-target="#loading-an-excel-file-directly">Loading an Excel file directly</a></li>
  </ul></li>
  <li><a href="#data-visualization" id="toc-data-visualization" class="nav-link" data-scroll-target="#data-visualization">Data Visualization</a>
  <ul class="collapse">
  <li><a href="#bar-graph" id="toc-bar-graph" class="nav-link" data-scroll-target="#bar-graph">Bar Graph</a></li>
  <li><a href="#scatter-plot-with-a-linear-fit" id="toc-scatter-plot-with-a-linear-fit" class="nav-link" data-scroll-target="#scatter-plot-with-a-linear-fit">Scatter Plot with a Linear Fit</a></li>
  </ul></li>
  <li><a href="#descriptive-statistics" id="toc-descriptive-statistics" class="nav-link" data-scroll-target="#descriptive-statistics">Descriptive statistics</a>
  <ul class="collapse">
  <li><a href="#min-max-median-mean" id="toc-min-max-median-mean" class="nav-link" data-scroll-target="#min-max-median-mean">Min, Max, Median &amp; Mean</a></li>
  <li><a href="#quantiles" id="toc-quantiles" class="nav-link" data-scroll-target="#quantiles">Quantiles</a></li>
  <li><a href="#standard-deviation-and-standard-error" id="toc-standard-deviation-and-standard-error" class="nav-link" data-scroll-target="#standard-deviation-and-standard-error">Standard Deviation and Standard Error</a></li>
  </ul></li>
  <li><a href="#inferential-statistics" id="toc-inferential-statistics" class="nav-link" data-scroll-target="#inferential-statistics">Inferential statistics</a>
  <ul class="collapse">
  <li><a href="#linear-regression" id="toc-linear-regression" class="nav-link" data-scroll-target="#linear-regression">Linear regression</a></li>
  <li><a href="#t-test" id="toc-t-test" class="nav-link" data-scroll-target="#t-test">T-test</a></li>
  <li><a href="#anova" id="toc-anova" class="nav-link" data-scroll-target="#anova">ANOVA</a></li>
  <li><a href="#chi-square---goodness-of-fit-test" id="toc-chi-square---goodness-of-fit-test" class="nav-link" data-scroll-target="#chi-square---goodness-of-fit-test">Chi-square - Goodness of Fit test</a></li>
  <li><a href="#chi-square---contingency-test" id="toc-chi-square---contingency-test" class="nav-link" data-scroll-target="#chi-square---contingency-test">Chi-square - Contingency test</a></li>
  </ul></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">R Intro</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Solomon Chak </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">February 27, 2023</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<p>This is a short introduction to R and statistics written to accompany introductory biology courses. This document will prepare you to perform statistic analysis and visualize results using R for most biology labs.</p>
<p>Why use R? See <a href="https://data-flair.training/blogs/why-learn-r/">here</a>.</p>
<section id="using-r-in-rstudio-locally-or-online" class="level2">
<h2 class="anchored" data-anchor-id="using-r-in-rstudio-locally-or-online">Using R in RStudio locally or online</h2>
<section id="installation-or-sign-up" class="level3">
<h3 class="anchored" data-anchor-id="installation-or-sign-up">Installation or sign up</h3>
<p>R is a command line program where you interact with it through text (command line) instead of a graphical user interface (e.g., Windows, Excel, etc.) There are two options for running R in this class. In both options, you will not interact directly with R, but through an integrated development environment called Rstudio on your computer or online (the cloud version of Rstudio is called Posit since 2022).</p>
<p>(1) You can download RStudio and install it on your computer. Follow the instructions <a href="https://posit.co/download/rstudio-desktop/">here</a> to download and install both R and RStudio.</p>
<p>(2) You can also use RStudio online. Sign up for an account <a href="https://posit.co/products/cloud/cloud/">here</a>. The “Cloud Free” option will be sufficient. Do not choose the PLUS or other options.</p>
</section>
<section id="project-setup-and-file-transfer" class="level3">
<h3 class="anchored" data-anchor-id="project-setup-and-file-transfer">Project setup and file transfer</h3>
<section id="local-option" class="level4">
<h4 class="anchored" data-anchor-id="local-option">Local option</h4>
<p>If you choose the local option, you should set up a project and a folder that is associated with this project where all files will be stored.</p>
<p>For example, create a folder on your desktop that is called “R_is_fun”. Start RStudio, click File &gt; New Project… and select “Existing Directory” and browse to the folder “R_is_fun”.</p>
<p>Then click “Create Project”. Now you can access all files in the folder “R_is_fun” (without indicating the full pathname) and everything you saved in R will also appear in this folder.</p>
</section>
<section id="online-option" class="level4">
<h4 class="anchored" data-anchor-id="online-option">Online option</h4>
<p>If you choose the cloud option, you will need to upload/download files to/from the cloud.</p>
<p>On posit.cloud, click “New Project” &gt; New RStudio Project on the upper right. Once the project is deployed, on the lower right panel, click the “upload” button and choose the file from your computer.</p>
<p>To download a file, check the box next to the file, click the “More” &gt; Export… and click “Download”.</p>
</section>
</section>
<section id="the-rstudio-interface" class="level3">
<h3 class="anchored" data-anchor-id="the-rstudio-interface">The RStudio Interface</h3>
<p>Let’s introduce what is being displayed in RStudio. Before we get started, click File &gt; New File &gt; R Script. This will result in a default four-panel interface <a href="#fig-RStudio_interface">Figure&nbsp;1</a>.</p>
<div id="fig-RStudio_interface" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="Rstudio_interface.png" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;1: The four-panel interface of RStudio.</figcaption><p></p>
</figure>
</div>
<ul>
<li><p>(A) The upper left is the R script panel. This is where you will write and save your R script or commands. The panel should be saved regularly, which serves as a record of all the commands that you have (or are planning) to run. For example, clicking File &gt; Save and giving it the name “R_is_fun” will save it as “R_is_fun.R” in your working directory. The scripts here are not being read by R until you click the “Run” button on the top right.</p></li>
<li><p>(B) The lower left is the R console, which is the innate command line interface of R. A command from the R script above will be displayed here when you click the “Run” button, which is when R “reads” your command. Any output or error from R will also be displayed here. You could type your command directly here, but it will not be saved in the R script.</p></li>
<li><p>(C) The upper right is the environment panel. Objects that are read or generated in R will be displayed here, along with any packages that you load and functions that you create.</p></li>
<li><p>(D) The lower right is the files panel. It displays the files in your working directory. It also displays figures in a “Plots” tab if your commands result in graphical outputs. The Help tab displays the manual for each package and command.</p></li>
</ul>
<p>For a more comprehensive introduction to RStudio, see <a href="https://education.rstudio.com/learn/beginner/">here</a>.</p>
</section>
<section id="using-packages" class="level3">
<h3 class="anchored" data-anchor-id="using-packages">Using packages</h3>
<p>Many packages are available to expand the basic functions of R.</p>
<p>To use these packages, you will need to install them first. Then you can load the package as libraries.</p>
<p>We will install a few packages that will be used in this document. You may be asked to select a mirror to download the packages.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">"ggplot2"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Installing package into '/cloud/lib/x86_64-pc-linux-gnu-library/4.2'
(as 'lib' is unspecified)</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">"readxl"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Installing package into '/cloud/lib/x86_64-pc-linux-gnu-library/4.2'
(as 'lib' is unspecified)</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">"Rmisc"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Installing package into '/cloud/lib/x86_64-pc-linux-gnu-library/4.2'
(as 'lib' is unspecified)</code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">"reshape"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Installing package into '/cloud/lib/x86_64-pc-linux-gnu-library/4.2'
(as 'lib' is unspecified)</code></pre>
</div>
</div>
<p>Then, we will load this packages such that functions from these packages can be used</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"ggplot2"</span>)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"readxl"</span>)</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"Rmisc"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: lattice</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: plyr</code></pre>
</div>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"reshape"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'reshape'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:plyr':

    rename, round_any</code></pre>
</div>
</div>
</section>
</section>
<section id="importing-data-into-r" class="level2">
<h2 class="anchored" data-anchor-id="importing-data-into-r">Importing data into R</h2>
<section id="preparing-a-.csv-file-from-excel" class="level3">
<h3 class="anchored" data-anchor-id="preparing-a-.csv-file-from-excel">Preparing a .csv file from Excel</h3>
<p>Your data should be entered and stored in spreadsheet programs such as Microsoft Excel before being imported into R. While R can read Excel files such as .xls and .xlsx, data are typically saved into a simpler text format such as .csv (comma-separated values), where each row appears in a new line and each column is separated by a comma (,) (<a href="#fig-excel">Figure&nbsp;2</a>).</p>
<div id="fig-excel" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="excel_vs_csv.png" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;2: Comparison of the same table in (A) Excel and (B) .csv format.</figcaption><p></p>
</figure>
</div>
<p>A spreadsheet in Excel can be exported into .csv by clicking File &gt; Save As… and selecting “CSV” in the drop-down manual under “File Format”.</p>
<p>Place the .csv file into your project’s directory (e.g., R_is_fun) or upload it to your project in posit.cloud. Now, you should see the .csv file listed in the lower right panel of RStudio (<strong>?@fig-file_panel</strong>).</p>
<p><img src="filepanel.png" id="fig-file_panel" class="img-fluid" alt="The file panel after placing the file “name.csv” into the working directory or after uploading it to posit.cloud.">.</p>
</section>
<section id="loading-a-.csv-file-into-r" class="level3">
<h3 class="anchored" data-anchor-id="loading-a-.csv-file-into-r">Loading a .csv file into R</h3>
<p>Note that while the name.csv file is in the file panel, it’s not being loaded into R yet. To do that, in the R script panel, type:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>data_name <span class="ot">=</span> <span class="fu">read.csv</span>(<span class="at">file =</span> <span class="st">"name.csv"</span>)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a><span class="co"># or just </span></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a><span class="co"># data_name = read.csv("name.csv")</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>What the code does is load “name.csv” into R and save it as an object called “data_name”. Now the object “data_name” should appear in the environment panel (<a href="#fig-env_panel">Figure&nbsp;3</a>).</p>
<div id="fig-env_panel" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="env_panel.png" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;3: A object loaded into R will appear in the environmental panel.</figcaption><p></p>
</figure>
</div>
<p>In the environmental panel, you can click on the object to open it in a new tab in the R script panel. Note that doing it actually sends a script to the R console as: <code>View(data_name).</code></p>
<p>You can also view the object within the R console by calling it directly:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>data_name</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  First_name Height_ft Age Academic_standing
1     Denzel       5.8  24         Sophomore
2     Claire       5.0  20            Junior
3       Jack       7.2  29        First-year
4     Quisha       5.7  26         Sophomore
5     Carlos       4.9  24        First-year
6      Julio       5.3  28         Sophomore
7     Hiromi       6.0  26            Senior
8      Jiang       5.5  28            Junior
9       Isha       4.4  18            Senior</code></pre>
</div>
</div>
<p>You can see that the file has loaded correctly. The 9 rows and 4 columns are present, as well as the column titles.</p>
<p>The object is a <em>dataframe</em>, which is a class of R object that stores table. See <a href="https://swcarpentry.github.io/r-novice-inflammation/13-supp-data-structures/">here</a> for other classes in R.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(data_name)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "data.frame"</code></pre>
</div>
</div>
<p>You can get more information of a dataframe with:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(data_name)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   9 obs. of  4 variables:
 $ First_name       : chr  "Denzel" "Claire" "Jack" "Quisha" ...
 $ Height_ft        : num  5.8 5 7.2 5.7 4.9 5.3 6 5.5 4.4
 $ Age              : int  24 20 29 26 24 28 26 28 18
 $ Academic_standing: chr  "Sophomore" "Junior" "First-year" "Sophomore" ...</code></pre>
</div>
</div>
<p>In some cases, you may need to add more arguments to <code>read.csv()</code>. Explore the documentation of this function.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">help</span>(<span class="st">"read.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>You can also search for it in the Help tab in the file panel. Another useful tips is that after you type help(, you can hit the tab key and RStudio will show the possible arguments for. Note also that RStudio will auto-complete the closing bracket for you.</p>
</section>
<section id="loading-an-excel-file-directly" class="level3">
<h3 class="anchored" data-anchor-id="loading-an-excel-file-directly">Loading an Excel file directly</h3>
<p>You can also directly import an Excel file into R with the help of the <code>readxl</code> package.</p>
<p>If you saved your Excel file as <code>name.xlsx</code>, then the command below will read the first sheet of an Excel file by default.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">read_xlsx</span>(<span class="at">path =</span> <span class="st">"name.xlsx"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 9 × 4
  First_name Height_ft   Age Academic_standing
  &lt;chr&gt;          &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt;            
1 Denzel           5.8    24 Sophomore        
2 Claire           5      20 Junior           
3 Jack             7.2    29 First-year       
4 Quisha           5.7    26 Sophomore        
5 Carlos           4.9    24 First-year       
6 Julio            5.3    28 Sophomore        
7 Hiromi           6      26 Senior           
8 Jiang            5.5    28 Junior           
9 Isha             4.4    18 Senior           </code></pre>
</div>
</div>
<p>Note that the above code does not save or overwrite the object <code>data_name</code> because we did not do the <code>data_name = read_xlsx(path = "name.xlsx")</code>. It simply read and output the result into the R console.</p>
</section>
</section>
<section id="data-visualization" class="level2">
<h2 class="anchored" data-anchor-id="data-visualization">Data Visualization</h2>
<p>Before you analyze the data, you should take a graphical look at your data. Here’re two common ways.</p>
<section id="bar-graph" class="level3">
<h3 class="anchored" data-anchor-id="bar-graph">Bar Graph</h3>
<p>A bar graph is used to visualize a continuous variable against a categorical variable.</p>
<p>While R can generate plots using the build-in functions, we will use the package <code>ggplot2</code> since it provides more ways to customize your plots.</p>
<p>Using <code>data_name</code> we can plot Age against Academic_standing. If you do not remember what are the names of your object, you can use <code>names()</code></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(data_name)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "First_name"        "Height_ft"         "Age"              
[4] "Academic_standing"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> data_name, <span class="fu">aes</span>(<span class="at">x =</span> Academic_standing, <span class="at">y =</span> Age)) <span class="sc">+</span> </span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="R_intro_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The code can be simplified using the idea of positional arguments:</p>
<p><code>ggplot(data_name, aes(Academic_standing, Age)) + geom_col()</code></p>
<p>Now you may want to (1) arrange your x-axis in a specific way, (2) get rid of the underscore in the x-axis, and (3) use different colors for each bar. You can do this by:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Setting Academic_standing as a factor with a specific order of levels.</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Note that this code modified data_name. </span></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a><span class="co"># There may be some cases where you don't want this change to be permanent, </span></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a><span class="co"># so you can then create a different object. </span></span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a><span class="co"># For example `data_name_sorted = data_name`</span></span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>data_name<span class="sc">$</span>Academic_standing <span class="ot">=</span> <span class="fu">factor</span>(data_name<span class="sc">$</span>Academic_standing, <span class="at">level =</span> <span class="fu">c</span>(<span class="st">"First-year"</span>, <span class="st">"Sophomore"</span>, <span class="st">"Junior"</span>, <span class="st">"Senior"</span>))</span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-10"><a href="#cb28-10" aria-hidden="true" tabindex="-1"></a><span class="co"># The main ggplot command is the same, but we have added:</span></span>
<span id="cb28-11"><a href="#cb28-11" aria-hidden="true" tabindex="-1"></a><span class="co"># labs(x = ..., y = ...) to specify  axis titles</span></span>
<span id="cb28-12"><a href="#cb28-12" aria-hidden="true" tabindex="-1"></a><span class="co"># fill = Academic_standing within aes to assign fill according to Academic_standing using the default color palette. </span></span>
<span id="cb28-13"><a href="#cb28-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Note that if you do color = , it will change the color of the boundary of the bar instead.</span></span>
<span id="cb28-14"><a href="#cb28-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-15"><a href="#cb28-15" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> data_name, <span class="fu">aes</span>(<span class="at">x =</span> Academic_standing, <span class="at">y =</span> Age, <span class="at">fill =</span> Academic_standing)) <span class="sc">+</span> </span>
<span id="cb28-16"><a href="#cb28-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>() <span class="sc">+</span></span>
<span id="cb28-17"><a href="#cb28-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x=</span><span class="st">"Academic standing"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="R_intro_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Note that in your R script, you can use <code>#</code> to add comments and notes. These will not be read by R.</p>
</section>
<section id="scatter-plot-with-a-linear-fit" class="level3">
<h3 class="anchored" data-anchor-id="scatter-plot-with-a-linear-fit">Scatter Plot with a Linear Fit</h3>
<p>A scatter plot is used to visualize a the relationship between two continuous variables.</p>
<p>Continuing to use <code>data_name</code>, we can first plot a scatter plot between <code>Height_ft</code> and <code>Age</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> data_name, <span class="fu">aes</span>(<span class="at">x =</span> Age, <span class="at">y =</span> Height_ft)) <span class="sc">+</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Height (feet)"</span>) <span class="co"># another way to change axis label</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="R_intro_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>To add a linear fit line, you can use <code>geom_smooth</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> data_name, <span class="fu">aes</span>(<span class="at">x =</span> Age, <span class="at">y =</span> Height_ft)) <span class="sc">+</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> lm) <span class="sc">+</span></span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Height (feet)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<p><img src="R_intro_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The figure above shows the linear fit line in blue and the standard error (SE) in grey. You can remove the SE and change the line to a grey, dashed line (e.g., to indicate a non-significant fit line). We will more probably evaluate the signifiance later under the section</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> data_name, <span class="fu">aes</span>(<span class="at">x =</span> Age, <span class="at">y =</span> Height_ft)) <span class="sc">+</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> lm, <span class="at">se =</span> F, <span class="at">color=</span><span class="st">"grey"</span>, <span class="at">linetype=</span><span class="st">"dashed"</span>) <span class="sc">+</span></span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Height (feet)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<p><img src="R_intro_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
</section>
<section id="descriptive-statistics" class="level2">
<h2 class="anchored" data-anchor-id="descriptive-statistics">Descriptive statistics</h2>
<p>When you first get your data, it will be wise to look at some numeric summaries of your dataframe.</p>
<p><code>summary</code> will give a summary of each column, depending on whether the column is numeric or categorical.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(data_name)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  First_name          Height_ft          Age         Academic_standing
 Length:9           Min.   :4.400   Min.   :18.00   First-year:2      
 Class :character   1st Qu.:5.000   1st Qu.:24.00   Sophomore :3      
 Mode  :character   Median :5.500   Median :26.00   Junior    :2      
                    Mean   :5.533   Mean   :24.78   Senior    :2      
                    3rd Qu.:5.800   3rd Qu.:28.00                     
                    Max.   :7.200   Max.   :29.00                     </code></pre>
</div>
</div>
<p>You can get the summary or specific summary statistics of each column using <code>$</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(data_name<span class="sc">$</span>Height_ft)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  4.400   5.000   5.500   5.533   5.800   7.200 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(data_name<span class="sc">$</span>Academic_standing)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>First-year  Sophomore     Junior     Senior 
         2          3          2          2 </code></pre>
</div>
</div>
<section id="min-max-median-mean" class="level3">
<h3 class="anchored" data-anchor-id="min-max-median-mean">Min, Max, Median &amp; Mean</h3>
<p>You can also these functions:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">min</span>(data_name<span class="sc">$</span>Age)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 18</code></pre>
</div>
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">max</span>(data_name<span class="sc">$</span>Age)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 29</code></pre>
</div>
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">median</span>(data_name<span class="sc">$</span>Age)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 26</code></pre>
</div>
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(data_name<span class="sc">$</span>Age)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 24.77778</code></pre>
</div>
</div>
</section>
<section id="quantiles" class="level3">
<h3 class="anchored" data-anchor-id="quantiles">Quantiles</h3>
<p>For quantiles:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">quantile</span>(data_name<span class="sc">$</span>Age)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  0%  25%  50%  75% 100% 
  18   24   26   28   29 </code></pre>
</div>
</div>
<p>Specific quantile:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">quantile</span>(data_name<span class="sc">$</span>Age, <span class="at">probs =</span> <span class="fl">0.95</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> 95% 
28.6 </code></pre>
</div>
</div>
</section>
<section id="standard-deviation-and-standard-error" class="level3">
<h3 class="anchored" data-anchor-id="standard-deviation-and-standard-error">Standard Deviation and Standard Error</h3>
<p>Standard deviation and standard error of the mean using base R:</p>
<p>Standard deviation:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(data_name<span class="sc">$</span>Age)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3.734226</code></pre>
</div>
</div>
<p>Standard error by calculating it from sd():</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(data_name<span class="sc">$</span>Age)<span class="sc">/</span><span class="fu">sqrt</span>(<span class="fu">length</span>(data_name))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.867113</code></pre>
</div>
</div>
<p>Standard error using the <code>summarySE</code> function in <code>Rmisc</code></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summarySE</span>(<span class="at">data =</span> data_name, <span class="at">measurevar =</span> <span class="st">"Age"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   .id N      Age       sd       se      ci
1 &lt;NA&gt; 9 24.77778 3.734226 1.244742 2.87038</code></pre>
</div>
</div>
<p>To output just the se:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summarySE</span>(<span class="at">data =</span> data_name, <span class="at">measurevar =</span> <span class="st">"Age"</span>)<span class="sc">$</span>se</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.244742</code></pre>
</div>
</div>
<p>To summarize within group (e.g., Academic_standing), we can also use the function in <code>Rmisc</code></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summarySE</span>(<span class="at">data =</span> data_name, <span class="at">measurevar =</span> <span class="st">"Age"</span>, <span class="at">groupvars =</span> <span class="st">"Academic_standing"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Academic_standing N  Age       sd       se        ci
1        First-year 2 26.5 3.535534 2.500000 31.765512
2         Sophomore 3 26.0 2.000000 1.154701  4.968275
3            Junior 2 24.0 5.656854 4.000000 50.824819
4            Senior 2 22.0 5.656854 4.000000 50.824819</code></pre>
</div>
</div>
</section>
</section>
<section id="inferential-statistics" class="level2">
<h2 class="anchored" data-anchor-id="inferential-statistics">Inferential statistics</h2>
<p>See this <a href="https://stats.oarc.ucla.edu/other/mult-pkg/whatstat/">link</a> for which statistical test to choose from based on the type of data. The link has example R codes as well! Below are a few commonly used ones.</p>
<section id="linear-regression" class="level3">
<h3 class="anchored" data-anchor-id="linear-regression">Linear regression</h3>
<p>Linear regression tests the relationship between two continuous variables. The analysis can estimate the a regression line that best fit the data using the least squares method (see <a href="https://www.jmp.com/en_us/statistics-knowledge-portal/what-is-regression/the-method-of-least-squares.html">here</a>). It also estimates the slope and intercept of the linear regression line and allows testing whether they are significantly different from zero.</p>
<p>In R the <code>lm</code> function can fit a number linear models, including linear regression.</p>
<p>To estimate the linear model to predict Height_ft (the response or dependent variable) by Age (the predictor or independent variable):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a>lm_HA <span class="ot">=</span> <span class="fu">lm</span>(<span class="at">formula =</span> Height_ft <span class="sc">~</span> Age, <span class="at">data =</span> data_name)</span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a>lm_HA</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Height_ft ~ Age, data = data_name)

Coefficients:
(Intercept)          Age  
     1.6538       0.1566  </code></pre>
</div>
</div>
<p>The output of the linear model shows the coefficients intercept and slope (under “Age”). But we can get much more out of <code>lm_HA</code> using <code>summary()</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm_HA)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Height_ft ~ Age, data = data_name)

Residuals:
    Min      1Q  Median      3Q     Max 
-0.7379 -0.5115 -0.0247  0.2753  1.0056 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)  
(Intercept)  1.65378    1.38315   1.196   0.2708  
Age          0.15657    0.05527   2.833   0.0253 *
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.5837 on 7 degrees of freedom
Multiple R-squared:  0.5341,    Adjusted R-squared:  0.4676 
F-statistic: 8.026 on 1 and 7 DF,  p-value: 0.0253</code></pre>
</div>
</div>
<p>Under “Coefficients”, it shows a t-test of whether the intercept and slope (Age) is significantly different from zero.</p>
<p>In the last three lines, it shows:</p>
<ul>
<li><p>Residual standard error: lower means better fit</p></li>
<li><p>Degrees of freedom: the maximum number of logically independent values</p></li>
<li><p>Multiple R-squared: the percentage of the response variable variation that a the model explains</p></li>
<li><p>Adjusted R-squared: adjusted for the number of terms in the model</p></li>
<li><p>Statistics of a F-test that evaluates the fit of the model.</p></li>
</ul>
<p>Although the F-test is at the end, it should be examined first to determine whether the linear model fits the data. Only when the model is well fitted, should you further interpret the significance of the intercept and slope.</p>
<p>In this example, the linear regression is significant because the p-value of the F test is lower than 0.05 (p = 0.0253), so we can continue to examine the intercept and slope.</p>
<p>The slope is 0.35657 (under “Estimate” in “Coefficient”) and the t-test indicate that it is significantly different from zero (p = 0.0253). Note that this p-value is the same when there is only one predictor variable. In multiple regression, there will be separate t-tests for each predictor variable.</p>
<p>Therefore we can write this to summarize the result and provide the statistical support: There is a positive relationship between height and age (slope = 0.357, F = 8.026, d.f. = 1 and 7, p = 0.025).</p>
<section id="visualization" class="level4">
<h4 class="anchored" data-anchor-id="visualization">Visualization</h4>
<p>Visualization for linear regression is shown above in <a href="#scatter-plot-with-a-linear-fit">Scatter Plot with a Linear Fit</a>.</p>
</section>
</section>
<section id="t-test" class="level3">
<h3 class="anchored" data-anchor-id="t-test">T-test</h3>
<p>A two sample T-test compares the means of two samples. The predictor (independent) variable is nominal and has two categories. The response (dependent) variable is continuous. In other words, a two sample t-test tests whether the two categories of the predictor variable affect the continuous response variable.</p>
<p>We will create a new variable called Age_group: A when Age &lt;= 25 and B when Age &gt; 25.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a>data_name<span class="sc">$</span>Age_group <span class="ot">&lt;-</span> <span class="fu">with</span>(data_name, <span class="fu">ifelse</span>(Age <span class="sc">&lt;=</span> <span class="dv">25</span>, <span class="st">"A"</span>, <span class="st">"B"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>You can <code>View(data_name)</code> to check that we now have a new column in <code>data_name</code>.</p>
<p>To test whether Height_ft is different between Age_group A and B, or whether Age_group affect Hr\eight_ft, we can use:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(Height_ft<span class="sc">~</span>Age_group, <span class="at">data =</span> data_name, <span class="at">alternative =</span> <span class="st">"two.sided"</span>, <span class="at">var.equal =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  Height_ft by Age_group
t = -2.0638, df = 6.9999, p-value = 0.07792
alternative hypothesis: true difference in means between group A and group B is not equal to 0
95 percent confidence interval:
 -1.9633556  0.1333556
sample estimates:
mean in group A mean in group B 
          5.025           5.940 </code></pre>
</div>
</div>
<p><code>alternative</code> can also be “greater” or “less” if you have an a priori reason to test a directional difference between groups.</p>
<p>In this case, the t-test is not statistically significant since the p-value is 0.07792.</p>
<section id="visualization-1" class="level4">
<h4 class="anchored" data-anchor-id="visualization-1">Visualization</h4>
<p>You can plot the continuous variable from two groups in a number of ways.</p>
<p>One way is to use a boxplot:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> data_name, <span class="fu">aes</span>(<span class="at">x =</span> Age_group, <span class="at">y =</span> Height_ft)) <span class="sc">+</span> </span>
<span id="cb69-2"><a href="#cb69-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb69-3"><a href="#cb69-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Age group"</span>, <span class="at">y =</span> <span class="st">"Height (feet)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="R_intro_files/figure-html/unnamed-chunk-29-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>You can even overlap your datapoints on top of the boxplot:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> data_name, <span class="fu">aes</span>(<span class="at">x =</span> Age_group, <span class="at">y =</span> Height_ft)) <span class="sc">+</span> </span>
<span id="cb70-2"><a href="#cb70-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb70-3"><a href="#cb70-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">width =</span> <span class="fl">0.1</span>, <span class="at">height =</span> <span class="dv">0</span>) <span class="sc">+</span> <span class="co"># this allows overlapping points to be seen</span></span>
<span id="cb70-4"><a href="#cb70-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Age group"</span>, <span class="at">y =</span> <span class="st">"Height (feet)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="R_intro_files/figure-html/unnamed-chunk-30-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
</section>
<section id="anova" class="level3">
<h3 class="anchored" data-anchor-id="anova">ANOVA</h3>
<p>Analysis of variance (ANOVA) is used similar to the t-test, but when the predictor variable has three or more categories.</p>
<p>To test whether Academic_standing affects Age:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a>anova_model <span class="ot">=</span> <span class="fu">aov</span>(<span class="at">formula =</span> Age <span class="sc">~</span> Academic_standing, <span class="at">data =</span> data_name)</span>
<span id="cb71-2"><a href="#cb71-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(anova_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                  Df Sum Sq Mean Sq F value Pr(&gt;F)
Academic_standing  3  27.06   9.019   0.534  0.679
Residuals          5  84.50  16.900               </code></pre>
</div>
</div>
<section id="visualization-2" class="level4">
<h4 class="anchored" data-anchor-id="visualization-2">Visualization</h4>
<p>Similar to the t-test, we can plot the data used for ANOVA:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> data_name, <span class="fu">aes</span>(<span class="at">x =</span> Academic_standing, <span class="at">y =</span> Age)) <span class="sc">+</span> </span>
<span id="cb73-2"><a href="#cb73-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb73-3"><a href="#cb73-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">width =</span> <span class="fl">0.1</span>, <span class="at">height =</span> <span class="dv">0</span>) <span class="sc">+</span> <span class="co"># this allows overlapping points to be seen</span></span>
<span id="cb73-4"><a href="#cb73-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Academic standing"</span>, <span class="at">y =</span> <span class="st">"Age"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="R_intro_files/figure-html/unnamed-chunk-32-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Note that showing the data points gives a more complete representation of our data. If you see only boxplot, you could imagine having a lot of data. But in fact, there are only 2-3 data point for each predictor variable. Some of them are even laying quite far apart from each other.</p>
</section>
</section>
<section id="chi-square---goodness-of-fit-test" class="level3">
<h3 class="anchored" data-anchor-id="chi-square---goodness-of-fit-test">Chi-square - Goodness of Fit test</h3>
<p>There are two types of Chi-Square tests, which are used when both the predictor and response variables are nominal.</p>
<p>The goodness of fit Chi-square test is used to test whether the observed result (i.e.&nbsp;collected during an experiment) is significantly different than the “expected” result.</p>
<p>For example, let’s first generate a count of <code>Age_group</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a>obs_age_group <span class="ot">=</span> <span class="fu">table</span>(data_name[,<span class="st">"Age_group"</span>])</span>
<span id="cb74-2"><a href="#cb74-2" aria-hidden="true" tabindex="-1"></a>obs_age_group</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
A B 
4 5 </code></pre>
</div>
</div>
<p>We can then test whether the observed distribution of <code>Age_group</code> is equally distributed among the two groups (i.e., 1:1) uisng <code>chisq.test()</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(<span class="at">x =</span> obs_age_group)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in chisq.test(x = obs_age_group): Chi-squared approximation may be
incorrect</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Chi-squared test for given probabilities

data:  obs_age_group
X-squared = 0.11111, df = 1, p-value = 0.7389</code></pre>
</div>
</div>
<p>Again, the null hypothesis is that the groups are equally distributed. The p-value is &gt; 0.05, which means that we have failed to reject the null hypothesis. Therefore, our observed distribution of Age_group is not significnatly different from 1:1.</p>
<p>If there is a priori reason that the distribution should be, for example, 3:1, we can modify the code to test this:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb79"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(<span class="at">x =</span> obs_age_group, <span class="at">p =</span> <span class="fu">c</span>(<span class="dv">3</span><span class="sc">/</span><span class="dv">4</span>,<span class="dv">1</span><span class="sc">/</span><span class="dv">4</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in chisq.test(x = obs_age_group, p = c(3/4, 1/4)): Chi-squared
approximation may be incorrect</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Chi-squared test for given probabilities

data:  obs_age_group
X-squared = 4.4815, df = 1, p-value = 0.03426</code></pre>
</div>
</div>
<p>In this second test, the p-value is &lt; 0.05, so we can reject the null hypothesis. Hence the distribution is significantly different from 3:1.</p>
<section id="visualization-3" class="level4">
<h4 class="anchored" data-anchor-id="visualization-3">Visualization</h4>
<p>You can plot the data for a goodness of fit Chi-square test by using the raw data in <code>data_name</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb82"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> data_name, <span class="fu">aes</span>(<span class="at">x =</span> Age_group)) <span class="sc">+</span> <span class="fu">geom_bar</span>() <span class="sc">+</span></span>
<span id="cb82-2"><a href="#cb82-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Age group"</span>, <span class="at">y =</span> <span class="st">"Count"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="R_intro_files/figure-html/unnamed-chunk-36-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
</section>
<section id="chi-square---contingency-test" class="level3">
<h3 class="anchored" data-anchor-id="chi-square---contingency-test">Chi-square - Contingency test</h3>
<p>The Contingency test (or the Test of Independence), tests if the difference between two groups (e.g., Age_group) is significantly different depending on (contingent on) another variable (e.g., Academic_standing). Or, put another way, you might want to determine if the frequency of outcomes for one set of observations matches those for another set of observations.</p>
<p>We will first reshape our data into a contingency table:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb83"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1" aria-hidden="true" tabindex="-1"></a>temp <span class="ot">=</span>  <span class="fu">melt</span>(data_name, <span class="at">measure.vars =</span> <span class="st">"Height_ft"</span>, <span class="at">id.vars =</span> <span class="fu">c</span>(<span class="st">"Age_group"</span>, <span class="st">"Academic_standing"</span>))</span>
<span id="cb83-2"><a href="#cb83-2" aria-hidden="true" tabindex="-1"></a>obs_table <span class="ot">=</span> <span class="fu">cast</span>(temp, Age_group<span class="sc">~</span>Academic_standing)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Aggregation requires fun.aggregate: length used as default</code></pre>
</div>
<div class="sourceCode cell-code" id="cb85"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb85-1"><a href="#cb85-1" aria-hidden="true" tabindex="-1"></a><span class="fu">rm</span>(temp)</span>
<span id="cb85-2"><a href="#cb85-2" aria-hidden="true" tabindex="-1"></a>obs_table</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Age_group First-year Sophomore Junior Senior
1         A          1         1      1      1
2         B          1         2      1      1</code></pre>
</div>
</div>
<p>We can then test the null hypothesis that the two variables <code>Age_group</code> and <code>Academic_standing</code> are independent.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb87"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb87-1"><a href="#cb87-1" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(obs_table)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in chisq.test(obs_table): Chi-squared approximation may be incorrect</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test

data:  obs_table
X-squared = 0.225, df = 3, p-value = 0.9735</code></pre>
</div>
</div>
<p>The p-value is &gt; 0.05. So we have failed to reject the null hypothesis. Hence the two variable are independent. In other words the distribution of <code>Age_group</code> is not dependent or affected by <code>Academic_standing</code>.</p>
<section id="visualization-4" class="level4">
<h4 class="anchored" data-anchor-id="visualization-4">Visualization</h4>
<p>You can plot the contingency table by:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb90"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb90-1"><a href="#cb90-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> data_name, <span class="fu">aes</span>(<span class="at">x =</span> Age_group)) <span class="sc">+</span> <span class="fu">geom_bar</span>() <span class="sc">+</span> <span class="fu">facet_grid</span>(<span class="sc">~</span>Academic_standing) <span class="sc">+</span></span>
<span id="cb90-2"><a href="#cb90-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Age group"</span>, <span class="at">y =</span> <span class="st">"Count"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="R_intro_files/figure-html/unnamed-chunk-39-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>